spring:
#Configurações do banco de dados
  datasource:
    url: jdbc:postgresql://localhost:5432/gameDigimonOnline
    username: postgres
    password: arisco2017
    driver-class-name: org.postgresql.Driver

#Configurações do Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Ativa o H2
  h2:
    console:
      enabled: true
      path: /h2-console

# Ativa o Flyway
flyway:
  enabled: true
  locations: classpath:db/migration
  database:
    compatibility-mode: postgresql

#Logging
  logging:
    level:
      root: INFO
      org.springframework.web: WARN
      br.com.digimon: DEBUG  # Mostra tudo do seu projeto em debug
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

#Configurações do Actuator
management:
  metrics:
    export:
        prometheus:
            enabled: true
  endpoints:
    web:
      exposure:
        include: "metrics,health,info"

#info:
#  app:
#    name: Game - Digimon Online
#    description: Jogo de Digimon Online.
#    version: 1.0.0

# Configurações do JWT
jwt:
  secret: d1g1monJw7K3ySuperSecretaSegura321!
  expiration: 3600000 # 1 hora em milissegundos