spring:
#Configurações do banco de dados
  datasource:
    url: jdbc:h2:mem:meubanco;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
#Configurações do Hibernate/JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Ativa o H2
  h2:
    console:
      enabled: true
      path: /h2-console

# Ativa o Flyway
flyway:
  enabled: true
  locations: classpath:db/migration